version: "3.7"
services:
  db:
    image: postgres
    container_name: some_postgres
    environment:
      POSTGRES_PASSWORD: <********>
      POSTGRES_DB: teste
      POSTGRES_USER: postgres
    restart: always
    ports:
      - "5432:5432"
  api:
    build: "./"
    container_name: java-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db